# Fly.io Configuration for Discord Bot Worker
# This configuration is for the Discord bot service
# Copy this to a separate directory or rename when deploying the bot

app = "market-sim-bot"
primary_region = "iad"  # Washington D.C. region

[build]
  dockerfile = "Dockerfile.bot"

[env]
  # Bot doesn't need a web port, but we'll set one for health checks
  PORT = "8080"

[[mounts]]
  source = "trading_data"
  destination = "/data"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  [services.autoscale]
    min_machines_running = 0  # Critical: Start at 0 for cost savings
    auto_stop_machines = "stop"
    auto_start_machines = true

[[vm]]
  cpu_kind = "shared"  # Cheapest option for free tier
  cpus = 1
  memory_mb = 256  # Minimal memory allocation

# Optional: Add health check if you modify bot to include basic HTTP endpoint
# [[services]]
#   internal_port = 8080
#   protocol = "tcp"
#   
#   [[services.http_checks]]
#     interval = "30s"
#     timeout = "2s"
#     grace_period = "5s"
#     restart_limit = 3
#     method = "get"
#     path = "/health"
#     protocol = "http"
