# .github/workflows/fly-deploy.yml
name: Fly Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group   # ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4

      # ⬇️ create a .env so validate.py passes
      - name: Write .env for validator
        run: |
          cat <<EOF > .env
          TOKEN=${{ secrets.TOKEN }}
          FINNHUB_API_KEY=${{ secrets.FINNHUB_API_KEY }}
          DISCORD_CHANNEL_ID=${{ secrets.DISCORD_CHANNEL_ID }}
          PRICE_CACHE_TTL=86400
          EOF

      # (optional) run your validator/tests here
      # - name: Validate
      #   run: |
      #     pip install -r requirements.txt
      #     python validate.py

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Fly deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy --remote-only
